name: areabaa
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Dependencies
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.5
  cloud_firestore: ^5.5.1
  firebase_auth: ^5.3.3

  # Local Notifications
  flutter_local_notifications: ^18.0.1

  # Utility Packages
  http: ^1.2.2
  url_launcher: ^6.0.20
  permission_handler: ^10.4.5
  flutter_dotenv: ^5.0.2

  # Contacts and Device Features
  contacts_service: ^0.6.3

  # State Management (Optional if needed later)
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/  # Add this if you use local images, fonts, or files.

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
